### ISSUE TITLE
missing_settings_key: existenceEndpoint3

### ISSUE THREAD

**Issue by Inversion-NL** [JohanBendz/com.philio#33]
Error: missing_settings_key: existenceEndpoint3
    at changedKeysArr.forEach (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:228:51)
    at Array.forEach (<anonymous>)
    at ZwaveDriver.settings (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:213:18)
    at /manager/drivers.js:1:3981
    at ZwaveDriver.fs.existsSync.drivers.(anonymous function).ready (/manager/drivers.js:1:2404)
    at clientDriverMessage (/manager/drivers.js:1:2949)
    at Homey.ready (/manager/drivers.js:1:446)
    at Object.Homey.ready (/homey.js:1:1073)
    at /manager/drivers.js:1:400
    at /helpers/client.js:1:1040

**Comment by Inversion-NL** [comment]
@jolny Do you know if you used a setting called existenceEndpoint3 in your driver?

**Comment by Inversion-NL** [comment]
A crash occurred for your app (version 0.0.22) at Nov 11, 2017 11:10 AM (UTC).

Homey software version: 1.5.3

Crash report: 
    Error: missing_settings_key: existenceEndpoint3
    at changedKeysArr.forEach (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:228:51)
    at Array.forEach (<anonymous>)
    at ZwaveDriver.settings (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:213:18)
    at /manager/drivers.js:1:3981
    at ZwaveDriver.fs.existsSync.drivers.(anonymous function).ready (/manager/drivers.js:1:2404)
    at clientDriverMessage (/manager/drivers.js:1:2949)
    at Homey.ready (/manager/drivers.js:1:446)
    at Object.Homey.ready (/homey.js:1:1073)
    at /manager/drivers.js:1:400
    at /helpers/client.js:1:1040

**Comment by Inversion-NL** [comment]
Dear Robin,

A crash occurred for your app (version 0.0.22) at Nov 11, 2017 11:15 AM (UTC).

Homey software version: 1.5.3

Crash report: 
    Error: missing_settings_key: existenceEndpoint3
    at changedKeysArr.forEach (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:228:51)
    at Array.forEach (<anonymous>)
    at ZwaveDriver.settings (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:213:18)
    at /manager/drivers.js:1:3981
    at ZwaveDriver.fs.existsSync.drivers.(anonymous function).ready (/manager/drivers.js:1:2404)
    at clientDriverMessage (/manager/drivers.js:1:2949)
    at Homey.ready (/manager/drivers.js:1:446)
    at Object.Homey.ready (/homey.js:1:1073)
    at /manager/drivers.js:1:400
    at /helpers/client.js:1:1040

**Comment by jolny** [comment]
OK, I'm guessing the only way to fix this permanently is to separate the PAN0x devices. Will have a look at it today, hopefully.

**Comment by Inversion-NL** [comment]
I was thinking about this.
How can there be a key missing from a setting.
We shouldn't be able to save it without a key in the first place. What do you think about this?

I think we should first ask someone from Athom to have a look at it.

**Comment by jolny** [comment]
Aah, are you @roadxy ? That makes sense.
Yes, agreed. Maybe they can help :)

**Comment by Inversion-NL** [comment]
Yes I am ;-)

**Comment by JohanBendz** [comment]
Fixed
